version: "3"

services:
  npm-registry:
    image: verdaccio/verdaccio:5.31
    restart: always
    ports:
      - "14873:4873"
    volumes:
      - ./conf:/verdaccio/conf
      - mirror-npm-vol:/verdaccio/storage
    env_file:
      - .env
    networks:
      - magic-network
volumes:
  mirror-npm-vol:
    external: true
networks:
  magic-network:
    external: true
