version: "3"

services:
  npm-registry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "14873:4873"
    volumes:
      - ./conf:/verdaccio/conf
      - mirror-npm-vol:/verdaccio/storage
      - ./uid_entrypoint:/opt/verdaccio/docker-bin/uid_entrypoint
    env_file:
      - .env
volumes:
  mirror-npm-vol:
    external: true
networks:
  magic-network:
    external: true
