version: "3"
services:
  maven-registry:
    image: sonatype/nexus3:3.69.0
    restart: always
    ports:
      - "18081:8081"
    volumes:
      - mirror-maven-vol:/nexus-data
    networks:
      - magic-network
volumes:
  mirror-maven-vol:
    external: true
networks:
  magic-network:
    external: true
