version: "3"
services:
  magic:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "37890:7890"
      - "9090"
    networks:
      - magic-network
networks:
  magic-network:
    external: true
