version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
notifications:
  endpoints:
    - name: my-webhook-endpoint
      url: http://mirror-docker-webhook:8080
      timeout: 500ms
      threshold: 5
      backoff: 1s
      eventtypes:
        - pull
