version: "3.0"
services:
  docker-registry:
    image: registry:2
    restart: always
    volumes:
      - mirror-docker-vol:/var/lib/registry
    networks:
      - magic-network
      - mirror-docker-network
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_LOG_FIELDS_SERVICE=registry
    ports:
      - 15000:5000
  docker-registry-proxy:
    image: shencangsheng/registry-mirror-proxy:1.0.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mirror-docker-network
    ports:
      - "5000:3000"
volumes:
  mirror-docker-vol:
    external: true
networks:
  magic-network:
    external: true
  mirror-docker-network:
